version: '3.8'

services:
  web:
    container_name: web
    build: ./docker
    ports:
      - 8888:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
        - db
    ports:
        - 8080:80
    environment:
        MYSQL_USERNAME: laravel
        MYSQL_ROOT_PASSWORD: password
        PMA_HOST: db
    volumes:
      - "./phpmyadmin/sessions:/sessions"
